# Site settings
author: Ezenwa Onukwue
title: Failing Fast
header-img: img/home-bg.png
email: ezenwa.onukwue@salesloft.com
copyright_name: Ezenwa Onukwue
description: > # this means to ignore newlines until "baseurl:"
  An introspective journey into Test Driven Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Zenwa5

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
